[package]
name = "email-delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.10.2"
env_logger = "0.11.7"
lettre = "0.11.15"
log = "0.4.26"
serde = { version = "1.0.219", features = ["derive"] }
